# -*- coding: utf-8 -*-
"""KNN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ise7rqtbX54IJfbHKJu6XpW0_R5yhJzj
"""

import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
from sklearn.model_selection import train_test_split, GridSearchCV

#Train KNN using GridSearchCV for HYPERTUNING 
def knn_with_gscv(x_train, y_train, x_test, y_test, n_neighbors_range=(1, 50)):
    knn = KNeighborsClassifier()
    param_grid = {'n_neighbors': np.arange(n_neighbors_range[0], n_neighbors_range[1])}
    gscv = GridSearchCV(knn, param_grid, cv=5, scoring='accuracy')
    gscv.fit(x_train, y_train)
    y_pred = gscv.predict(x_test)
    accuracy = metrics.accuracy_score(y_test, y_pred)

    return accuracy, gscv.best_estimator_, gscv.best_params_

#Load data from CSV's
x_train = pd.read_csv("x_train.csv")
x_test = pd.read_csv("x_test.csv")
y_train = pd.read_csv("y_train.csv").squeeze()
y_test = pd.read_csv("y_test.csv").squeeze()

#Train and print the accuracy
accuracy, knn_model, best_params = knn_with_gscv(x_train, y_train, x_test, y_test)
print("Accuracy:", accuracy)
print("Best Parameters:", best_params)